"""Shared validation orchestration for the CLI and local demo interface."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

import pandas as pd

from src.ai_module import explain_issue
from src.loader import load_csv
from src.report import build_validation_report, save_report
from src.schemas import build_issue, build_processing_issue
from src.validator import run_validations


@dataclass(slots=True)
# This transport object intentionally keeps execution metadata together for
# the CLI and API layers.
# pylint: disable=too-many-instance-attributes
class ValidationExecutionResult:
    """Outcome of the deterministic validation stage."""

    success: bool
    dataframe: pd.DataFrame | None
    issues: list[dict[str, Any]]
    configuration: dict[str, Any]
    executed_checks: list[str]
    validation_status: str
    run_stage: str
    error: Exception | None = None


@dataclass(slots=True)
class ValidationRunResult:
    """Outcome of a validation run.

    Attributes:
        success: Whether the validation completed successfully.
        output_path: JSON report path written for the run.
        report: Final report payload generated by the run.
        error: Exception raised during the run, if any.
    """

    success: bool
    output_path: Path
    report: dict[str, Any]
    error: Exception | None = None


def validate_input(
    *,
    input_path: str | Path,
    key_columns: Sequence[str] | None = None,
    value_column: str | None = None,
    time_column: str | None = None,
) -> ValidationExecutionResult:
    """Run deterministic validation without persistence or placeholder enrichment.

    Args:
        input_path: Path to the input CSV file.
        key_columns: Optional key columns used for duplicate detection.
        value_column: Optional numeric column used for outlier detection.
        time_column: Optional date column used for gap detection.

    Returns:
        A structured result for the validation stage.
    """
    configuration = {
        "key_columns": list(key_columns or []),
        "value_column": value_column,
        "time_column": time_column,
    }
    executed_checks = _build_executed_checks(
        key_columns=key_columns or [],
        value_column=value_column,
        time_column=time_column,
    )

    try:
        dataframe = load_csv(input_path)
    except (FileNotFoundError, OSError, TypeError, ValueError) as error:
        return ValidationExecutionResult(
            success=False,
            dataframe=None,
            issues=[],
            configuration=configuration,
            executed_checks=executed_checks,
            validation_status="not_run",
            run_stage="load",
            error=error,
        )

    try:
        issues = run_validations(
            dataframe,
            key_columns=key_columns,
            value_column=value_column,
            time_column=time_column,
        )
    except (FileNotFoundError, OSError, TypeError, ValueError) as error:
        return ValidationExecutionResult(
            success=False,
            dataframe=dataframe,
            issues=[],
            configuration=configuration,
            executed_checks=executed_checks,
            validation_status="failed",
            run_stage="validation",
            error=error,
        )

    return ValidationExecutionResult(
        success=True,
        dataframe=dataframe,
        issues=list(issues),
        configuration=configuration,
        executed_checks=executed_checks,
        validation_status="failed" if issues else "passed",
        run_stage="completed",
    )


def run_validation(
    *,
    input_path: str | Path,
    output_path: str | Path,
    key_columns: Sequence[str] | None = None,
    value_column: str | None = None,
    time_column: str | None = None,
) -> ValidationRunResult:
    """Run validation, enrich issues, and persist the JSON report.

    Args:
        input_path: Path to the input CSV file.
        output_path: Path to the output JSON report.
        key_columns: Optional key columns used for duplicate detection.
        value_column: Optional numeric column used for outlier detection.
        time_column: Optional date column used for gap detection.

    Returns:
        A structured result describing the run outcome.
    """
    execution = validate_input(
        input_path=input_path,
        key_columns=key_columns,
        value_column=value_column,
        time_column=time_column,
    )

    if not execution.success:
        assert execution.error is not None
        failure_issue = build_processing_issue(
            execution.error,
            input_path=input_path,
            stage=execution.run_stage,
        )
        failure_issue["ai_explanation"] = explain_issue(failure_issue)
        failure_report = build_validation_report(
            input_path,
            execution.dataframe,
            [failure_issue],
            run_status="failed",
            validation_status=execution.validation_status,
            run_stage=execution.run_stage,
            configuration=execution.configuration,
            executed_checks=execution.executed_checks,
        )
        try:
            output_file = save_report(failure_report, output_path)
        except OSError as error:
            return ValidationRunResult(
                success=False,
                output_path=Path(output_path),
                report=failure_report,
                error=error,
            )
        return ValidationRunResult(
            success=False,
            output_path=output_file,
            report=failure_report,
            error=execution.error,
        )

    enriched_issues = _enrich_issues(execution.issues)
    report = build_validation_report(
        input_path,
        execution.dataframe,
        enriched_issues,
        run_status="succeeded",
        validation_status=execution.validation_status,
        run_stage="completed",
        configuration=execution.configuration,
        executed_checks=execution.executed_checks,
    )

    try:
        output_file = save_report(report, output_path)
    except OSError as error:
        write_issue = build_issue(
            code="report_write_failure",
            category="pipeline",
            severity="error",
            message=str(error),
            stage="write",
            metrics={},
            context={
                "input_path": str(input_path),
                "output_path": str(output_path),
                "exception_type": type(error).__name__,
            },
        )
        failure_report = build_validation_report(
            input_path,
            execution.dataframe,
            _enrich_issues([*execution.issues, write_issue]),
            run_status="failed",
            validation_status=execution.validation_status,
            run_stage="write",
            configuration=execution.configuration,
            executed_checks=execution.executed_checks,
        )
        return ValidationRunResult(
            success=False,
            output_path=Path(output_path),
            report=failure_report,
            error=error,
        )

    return ValidationRunResult(
        success=True,
        output_path=output_file,
        report=report,
    )


def _build_executed_checks(
    *,
    key_columns: Sequence[str],
    value_column: str | None,
    time_column: str | None,
) -> list[str]:
    """Build the list of enabled validation checks for the current run."""
    checks = ["missing_values"]

    if key_columns:
        checks.append("duplicate_rows")

    if value_column:
        checks.append("numeric_outlier")

    if time_column:
        checks.append("time_series_gap")

    return checks


def _enrich_issues(issues: Sequence[dict[str, Any]]) -> list[dict[str, Any]]:
    """Attach placeholder explanation data to validation issues."""
    enriched_issues: list[dict[str, Any]] = []

    for issue in issues:
        enriched_issue = dict(issue)
        enriched_issue["ai_explanation"] = explain_issue(issue)
        enriched_issues.append(enriched_issue)

    return enriched_issues
